### ISSUE TITLE
Search operator deployment ignores replicaCount, defaults to 1

### ISSUE THREAD

**Issue by sankfred** [stolostron/search-v2-operator#456]
Please address the hard coded [replica](https://github.com/stolostron/search-v2-operator/blob/main/addon/manifests/chart/templates/deployment.yaml#L10) in the deployment template. The searchapi accepts the [replicaCount](https://github.com/stolostron/search-v2-operator/blob/main/api/v1alpha1/search_types.go#L95-L99); however, there is no corresponding replica value in the values file, resulting in pods deployed with single replica.  [replicas](https://github.com/stolostron/search-v2-operator/blob/main/addon/manifests/chart/values.yaml) is missing from the values file: 

This issue arises due to the hardcoded replicaCount value in deployment.yaml file: [deployment.yaml](https://github.com/stolostron/search-v2-operator/blob/main/addon/manifests/chart/templates/deployment.yaml#L10)

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: "search"
spec:
  replicas: 1
```

```
search-v2-operator (main) $ grep -ir replica addon/manifests/chart/values.yaml 
search-v2-operator (main) $
```
